# Generated by Django 3.2.19 on 2023-06-28 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CashInOut', '0002_auto_20230628_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='cashin',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CashInOut.profile'),
        ),
        migrations.AlterField(
            model_name='cashout',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CashInOut.profile'),
        ),
    ]
