# Generated by Django 3.2.19 on 2023-06-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashInOut', '0003_auto_20230628_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cash_in_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_out_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
