# Generated by Django 3.2.19 on 2023-07-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashInOut', '0004_dailyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='cashin',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='cashout',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='cash_in_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='cash_out_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
